# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PrawClient": "00_firsttry.ipynb",
         "storage_path": "00_firsttry.ipynb",
         "natural_path": "00_firsttry.ipynb",
         "bad_natural_path": "00_firsttry.ipynb",
         "steroids_path": "00_firsttry.ipynb",
         "bad_steroids_path": "00_firsttry.ipynb",
         "uncertain_path": "00_firsttry.ipynb",
         "irrelevant_path": "00_firsttry.ipynb",
         "get_thumbnail_index": "00_firsttry.ipynb",
         "get_thumbnail": "00_firsttry.ipynb",
         "get_images": "00_firsttry.ipynb",
         "SubmissionsHandler": "03_submissionshandler.ipynb",
         "create_db": "05_database.ipynb",
         "mapper_registry": "05_database.ipynb",
         "Base": "05_database.ipynb",
         "database_path": "05_database.ipynb",
         "engine": "05_database.ipynb",
         "Session": "05_database.ipynb",
         "Label": "06_submission.ipynb",
         "Submission": "06_submission.ipynb"}

modules = ["firsttry.py",
           "pushshift.py",
           "submissionshandler.py",
           "database.py",
           "submission.py"]

doc_url = "https://cedarmora.github.io/steroidsornot/"

git_url = "https://github.com/cedarmora/steroidsornot/tree/master/"

def custom_doc_links(name): return None
