# AUTOGENERATED! DO NOT EDIT! File to edit: 05_database.ipynb (unless otherwise specified).

__all__ = ['database_path', 'engine', 'mapper_registry', 'Base']

# Cell

from sqlalchemy.orm import registry
from sqlalchemy import create_engine
from pathlib import Path

# Cell

database_path = Path('./data/db.db')

engine = create_engine(f'sqlite+pysqlite:///{database_path}', echo=True, future=True)

mapper_registry = registry()
Base = mapper_registry.generate_base()

Base.metadata.create_all(engine)