# AUTOGENERATED! DO NOT EDIT! File to edit: 05_database.ipynb (unless otherwise specified).

__all__ = ['create_db', 'mapper_registry', 'Base', 'database_path', 'engine', 'Session']

# Cell

from sqlalchemy.orm import registry
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from pathlib import Path

# Cell

mapper_registry = registry()
Base = mapper_registry.generate_base()

database_path = Path('./data/db.db')

engine = create_engine(f'sqlite+pysqlite:///{database_path}', echo=True, future=True)

# create a configured "Session" class
Session = sessionmaker(bind=engine)

def create_db(base, engine):
    base.metadata.create_all(engine)