# AUTOGENERATED! DO NOT EDIT! File to edit: 00_firsttry.ipynb (unless otherwise specified).

__all__ = ['PrawClient']

# Cell
from fastbook import *
from fastai.vision.widgets import *
# Loads environment variables from .env file

import os
import praw
import requests
from PIL import Image
from io import BytesIO
from dotenv import load_dotenv

# Cell
class PrawClient():
    def __init__(self):
        load_dotenv()
        self.client_id = os.environ.get('REDDIT_CLIENT_ID')
        self.client_secret = os.environ.get('REDDIT_CLIENT_SECRET')
        self.user_agent = 'User-Agent: Steroid detector bot by /u/thetreecycle'
        # Output client_id to see if it's working
        print(f'Starting instance with client_id {self.client_id}')

    def reddit(self):
        return praw.Reddit(
            client_id=self.client_id,
            client_secret=self.client_secret,
            user_agent=self.user_agent,
        )
    def subreddit(self, subreddit):
        return self.reddit().subreddit(subreddit)