# AUTOGENERATED! DO NOT EDIT! File to edit: 01_pushshift.ipynb (unless otherwise specified).

__all__ = ['unpickle', 'select_mostly_useful']

# Cell

# Loads environment variables from .env file

import os
import praw
import requests
import time
import datetime
import sys
import pickle
from requests.adapters import HTTPAdapter
from collections import Counter
import webbrowser

# Cell
def unpickle(path):
    pickled_list = []
    with open(path, "rb") as file:
        while 1:
            try:
                pickled_list += pickle.load(file)
            except EOFError:
                break

    print(f'Unpickled {len(pickled_list)} objects.')
    return pickled_list

# Cell
def select_mostly_useful(posts):
    '''
    Remove mostly invalid posts, stuff like:
    few comments (so no label),
    no selftext are often not useful
    post was deleted or removed

    It's not a complete solution, as the pushshift data
    doesn't get updated when the post changes, so there
    are many posts which were deleted after fact.
    '''
    mostly_useful = []
    for post in posts:
        if (post['num_comments'] >= 2 and
                'selftext' in post and
                post['selftext'] != '[deleted]' and
                post['selftext'] != '[removed]' and
                post.get('removed_by_category') == None and
                post.get('link_flair_text') != 'Meme' and
                post.get('domain') == 'i.redd.it'):
            mostly_useful.append(post)
    return mostly_useful


# 34258