# AUTOGENERATED! DO NOT EDIT! File to edit: 06_submission.ipynb (unless otherwise specified).

__all__ = ['Label', 'Submission']

# Cell
import enum
from sqlalchemy import Table, Column, Integer, Enum, JSON, Text
from .database import Base

# Cell
class Label(enum.Enum):
    natural = 1
    steroids = 2
    uncertain = 3
    irrelevant = 4
    deleted = 5
    autoremoved = 6

# Cell
class Submission(Base):
    __tablename__ = "submission"

    id = Column(Integer, primary_key=True)
    label = Column(Enum(Label))
    data = Column(JSON)
    image_path = Column(Text)

    def __repr__(self):
        return f"Submission(id={self.id!r}, label={self.label!r}, data={self.data!r})"